# 应用程序名称
app_name: "Go Starter Service"
# 运行模式（release / test / debug)
run_mode: "debug"

server:
  # 应用运行地址（本机：127.0.0.1，所有地址：0.0.0.0）
  host: "127.0.0.1"
  # 应用运行端口
  port: "6280"

orm:
  # 调试模式
  debug: true
  # 数据库类型（postgres / mysql）
  dialect: "postgres"
  # 数据源名称(postgres: "host=db_host port=db_port dbname=db_name user=db_user password=db_pass sslmode=disable TimeZone=Asia/Shanghai" / mysql: "db_user:db_pass@tcp(db_host:db_port)/db_name?params")
   dsn: "host=db_host port=db_port dbname=db_name user=db_user password=db_pass sslmode=disable TimeZone=Asia/Shanghai"
  # 最大连接数
  max_open_conn: 64
  # 连接可以充用的最长时间（秒）
  max_life_time: 7200
  # 空闲连接最大数量
  max_idle_conn: 16
  # 表前缀
  table_prefix: ""
  # 是否启用自动映射表结构
  auto_migrate: true

logger:
  # 日志级别(1:fatal 2:error,3:warn,4:info,5:debug)
  level: 5
  # 日志格式（支持输出格式：text/json）
  format: "text"
  # 日志输出(支持：stdout/stderr/file)
  output: "stdout"
  # 指定日志输出的文件路径
  output_file: "logs/go-starter.log"

casbin:
  path:

jwt:
  secret: "" # openssl passwd -stdin < <(echo) | base64 | shasum
  exp_time: 48 # hours

redis:
  # 地址
  host: "127.0.0.1"
  # 密码
  password: ""
  # 端口
  port: "6378"
  # 数据库索引 0 - 15
  db: 0
