// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SampleColumns holds the columns for the "sample" table.
	SampleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "primary key"},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "name"},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "content, big text"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "created at"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "updated at"},
	}
	// SampleTable holds the schema information for the "sample" table.
	SampleTable = &schema.Table{
		Name:       "sample",
		Columns:    SampleColumns,
		PrimaryKey: []*schema.Column{SampleColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sample_id",
				Unique:  false,
				Columns: []*schema.Column{SampleColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SampleTable,
	}
)

func init() {
	SampleTable.Annotation = &entsql.Annotation{
		Table: "sample",
	}
}
